TNG/ngqp

projects/ngqp-demo/src/app/test-router-adapter.service.ts
projects/ngqp/core/src/lib/directives/query-param-group.service.ts
projects/ngqp/core/src/lib/router-adapter/router-adapter.interface.ts
projects/ngqp/core/src/test/back-forward.spec.ts

This pull request relates to or closes the following issues: #73

fix(core): Do not detect non-imperative navigations as synthetic

---

CHANGELOG.md
DCO
NOTICE
README.md
package.json
projects/ngqp-demo/src/app/demo.component.html
projects/ngqp-demo/src/app/docs-items/getting-help/getting-help-docs.component.html
projects/ngqp-demo/src/app/home/home.component.html
projects/ngqp/core/package.json

Prepare move of repository to @TNG

---

package.json
projects/ngqp/core/.compodocrc.json
projects/ngqp/core/tsconfig.compodoc.json
yarn.lock

Compodoc 1.1.8

---

projects/ngqp-demo/src/app/demo.module.ts
projects/ngqp-demo/src/app/docs-items/examples/add-remove-parameter/add-remove-parameter-example.component.html
projects/ngqp-demo/src/app/docs-items/examples/add-remove-parameter/add-remove-parameter-example.component.ts
projects/ngqp-demo/src/app/docs-items/model-usage/model-usage-docs.component.html
projects/ngqp/core/src/lib/directives/query-param-group.service.ts
projects/ngqp/core/src/lib/directives/query-param-name.directive.ts
projects/ngqp/core/src/lib/model/query-param-group.spec.ts
projects/ngqp/core/src/lib/model/query-param-group.ts
projects/ngqp/core/src/lib/model/query-param.ts
projects/ngqp/core/src/test/group-add.spec.ts
projects/ngqp/core/src/test/group-remove.spec.ts

Dynamically add or remove QueryParam

---

scripts/prepare-release.sh
scripts/publish-release.sh

fix(other): Push only after release is published

---

.travis.yml

fix(travis): Only trigger branch builds for master

---

projects/ngqp/core/src/lib/directives/query-param.directive.ts
projects/ngqp/core/src/test/standalone.spec.ts

This pull request relates to or closes the following issues: closes #98

Support changing bound standalone parameters

---

package.json
yarn.lock

chore(docs): Update to compodoc 1.1.9

---

scripts/prepare-release.sh

fix(scripts): Sign release commits

---

projects/ngqp/core/src/lib/directives/query-param-group.service.ts
projects/ngqp/core/src/lib/directives/query-param.directive.ts
projects/ngqp/core/src/lib/model/query-param-group.ts

fix(core): Prefer unknown over any where possible

---

.travis.yml
commitlint.config.js
package.json
yarn.lock

Add commitlint

---

projects/ngqp/core/src/lib/directives/query-param-group.directive.ts
projects/ngqp/core/src/lib/directives/query-param-name.directive.ts
projects/ngqp/core/src/lib/directives/query-param.directive.ts

fix(docs): Hide directive constructors from API docs

---

projects/ngqp/core/package.json
projects/ngqp/core/yarn.lock

chore(deps): Upgrade schematics-utilities to 1.1.2

---

projects/ngqp-demo/src/app/demo.module.ts
projects/ngqp-demo/src/app/docs-items/configuration/query-param/query-param-configuration-docs.component.html
projects/ngqp-demo/src/app/docs-items/examples/partition-example/partition-example.component.html
projects/ngqp-demo/src/app/docs-items/examples/partition-example/partition-example.component.ts
projects/ngqp/core/src/lib/directives/query-param-group.service.ts
projects/ngqp/core/src/lib/model/model.ts
projects/ngqp/core/src/lib/model/query-param-group.ts
projects/ngqp/core/src/lib/model/query-param-opts.ts
projects/ngqp/core/src/lib/model/query-param.spec.ts
projects/ngqp/core/src/lib/model/query-param.ts
projects/ngqp/core/src/lib/query-param-builder.service.ts
projects/ngqp/core/src/lib/types.ts
projects/ngqp/core/src/test/partitioned.spec.ts

Binding one component to multiple parameters – Solution #2

---

projects/ngqp/core/src/lib/model/query-param.ts
projects/ngqp/core/tsconfig.lib.json

#117: Activate some strict TS settings

---

projects/ngqp/core/src/lib/model/query-param.ts
projects/ngqp/core/src/lib/query-param-builder.service.ts
projects/ngqp/core/tsconfig.lib.json

chore: Enable strictFunctionTypes

---

projects/ngqp/core/src/lib/accessors/multi-select-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/multi-select-option.directive.ts
projects/ngqp/core/src/lib/accessors/number-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/range-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/select-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/select-option.directive.ts
projects/ngqp/core/src/lib/accessors/util.ts
projects/ngqp/core/src/lib/directives/query-param-group.directive.ts
projects/ngqp/core/src/lib/directives/query-param-group.service.ts
projects/ngqp/core/src/lib/directives/query-param-name.directive.ts
projects/ngqp/core/src/lib/directives/query-param.directive.ts
projects/ngqp/core/src/lib/model/query-param-opts.ts
projects/ngqp/core/src/lib/model/query-param.ts
projects/ngqp/core/src/lib/router-adapter/router-adapter.interface.ts
projects/ngqp/core/src/lib/types.ts
projects/ngqp/core/tsconfig.lib.json
tslint.json

#117: Strict TypeScript mode

---

projects/ngqp/core/src/lib/accessors/checkbox-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/default-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/multi-select-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/number-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/range-control-value-accessor.directive.ts
projects/ngqp/core/src/lib/accessors/select-control-value-accessor.directive.ts

refactor: don't export providers and type them better

---

projects/ngqp/core/package.json
projects/ngqp/core/schematics/ng-add/index.ts

closes #32
BREAKING CHANGES: v1

chore: prepare release v1

---

package.json
yarn.lock

chore: update compodoc to 1.1.10

---

.travis.yml

chore: pin node version used by Travis

---

projects/ngqp/core/package.json
projects/ngqp/core/schematics/ng-add/index.ts
projects/ngqp/core/src/lib/query-param-builder.service.ts

chore: support Angular 9

---

package.json
scripts/prepare-release.sh

chore: do not compile with Ivy

---

package.json

chore: build as prod when releasing demo

---

README.md

Signed-off-by: Ingo Bürk <ingo+github@buerk.io>

fix(docs): remove erroneous "www."
